accounts/urls.py
from django.urls import path, include
from . import views

from django.contrib.auth.views import LogoutView


app_name = 'accounts'

urlpatterns = [
    
    path('register/',views.UserRegisterView.as_view(), name='register'),
    path('login/',views.CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

market/urls.py
from django.urls import path, include
from . import views

app_name = "market"

urlpatterns = [
    path('', views.home, name="home"),
    path('shop/', views.ShopListView.as_view(), name="shop"),
    path('cart/', views.cart, name="cart"),
    path('about/', views.AboutView.as_view(), name="about"),
    path('contanct/', views.ContanctView.as_view(), name="contanct"),
    path('cart/checkout', views.checkout, name="checkout"),
    path('update_item/', views.updateItem, name="updateItem"),
    path('process_order/', views.process_order, name="updateItem"),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('accounts/', include("accounts.urls")),
    path('admin/', admin.site.urls),
    path('', include("market.urls", namespace="market")),
    
    
]

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/models.py
from django.db import models
from django.contrib.auth.models import User

from django.utils.text import slugify
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)

class Product(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/')
    slug = models.SlugField(max_length=255, null=True,blank=True)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    category = models.ForeignKey('Category', related_name='product', on_delete=models.CASCADE)
    
    
    def __str__(self):
        return self.title
    
    def save(self,*args, **kwargs):
        self.slug = slugify(self.title)
        super(Product, self).save(*args, **kwargs)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, null=True, blank=True)
    
    class Meta:
        verbose_name_plural = 'categories'
        
    def save(self,*args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)  

    def __str__(self):
        return self.name
      
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=254, null=True)
    
    def __str__(self):
        return self.name
    
    
@receiver(post_save, sender=User)
def create_user_account(sender, instance, created, **kwargs):
    if created:
        Customer.objects.create(
            user=instance,
            name=instance) 
        
    
    
class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False ,null=True, blank=True)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)
    
    @property 
    def cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([ item.total for item in orderitems])
        
        return total
    
    @property 
    def cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([ item.quantity for item in orderitems])
        
        return total

    
class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField(default=0)
    date_added  = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    
    @property 
    def total(self):
        total_price = self.product.price * self.quantity
        return total_price
    
    
    def __str__(self):
        return self.order

class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added  = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.address

market/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView

import json
import datetime

from .models import Order, OrderItem, Product, Category, ShippingAddress

# Create your views here.
def home(request):
    data = Product.objects.all()
    products = []
    counter = 0
    for i in data:
        if counter >= 6:
            break
        products.append(i)
        counter+=1
    
    if request.user.is_authenticated:
        customer = request.user.customer 
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        cartItems = order.cart_items
        
    else:
        items = []
        order = {'cart_total':0, 'cart_items':0}
        cartItems = order['cart_items']     
        
    context = {"products":products, 'cartItems':cartItems}
    return render(request,"market/index.html",context)


class ShopListView(ListView):
    model = Product
    template_name = "market/shop.html"
    context_object_name = "products"
    paginate_by = 6
    
        
def cart(request):
    
    if request.user.is_authenticated:
        customer = request.user.customer 
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.cart_items
    else:
        items = []
        order = {'cart_total':0, 'cart_items':0}
        cartItems = order['cart_items']
        
    context = {'items': items, 'order':order, 'cartItems':cartItems}
    return render(request, 'market/cart.html', context)
   
   
def checkout(request):
    if request.user.is_authenticated:
        customer = request.user.customer 
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.cart_items
    else:
        items = []
        order = {'cart_total':0, 'cart_items':0}
        cartItems = order['cart_items']
        
    context = {'items': items, 'order':order, 'cartItems':cartItems}
    return render(request, 'market/checkout.html', context)
 
    
class AboutView(TemplateView):
    template_name = 'market/about.html'   
   
    
class ContanctView(TemplateView):
    template_name = 'market/contact.html'

    
def updateItem(request):
    data = json.loads(request.body)
    
    productId = data['productId']
    action = data['action']
    
    customer = request.user.customer
    product = Product.objects.get(id=productId)
    
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == "add":
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == "remove":
        orderItem.quantity = (orderItem.quantity - 1)
        
    orderItem.save()
    
    if orderItem.quantity <= 0:
        orderItem.delete()
    
    return JsonResponse("Item was added", safe=False)


def process_order(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        total = float(data['form']['total'])
        order.transaction_id = transaction_id
        
        if total == float(order.cart_total):
            order.complete = True 
            
        order.save()
        
        ShippingAddress.objects.create(
            customer = customer,
            order = order,
            address = data['shipping']['address'],
            city = data['shipping']['city'],
            state = data['shipping']['state'],
            zipcode = data['shipping']['zipcode']
        )
        
    else:
        print('user is not logged in')
    

    return JsonResponse("payment complete", safe=False)



    

market/templates/market/about.html
{% include 'head.html' %}
{% load static %}
{% block content %}
{% include 'shop_navbar.html' %}
<div class="section about ">
    <div class="container">
        <div class="row">
           <div class="col-12">
               <div class="titlepage">
                <h2><strong class="black"> About</strong>  Us</h2>
                <span>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected randomised words which don't look even slightly believable</span>
             </div>
           </div>
        </div>
    </div>
 </div>
 <section >
    <div id="main_slider" class="section carousel slide banner-main" data-ride="carousel">
       <ol class="carousel-indicators">
          <li data-target="#main_slider" data-slide-to="0" class="active"></li>
          <li data-target="#main_slider" data-slide-to="1"></li>
          <li data-target="#main_slider" data-slide-to="2"></li>
       </ol>
       <div class="carousel-inner">
          <div class="carousel-item active">
             <div class="container">
                <div class="row marginii">
                   <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                      <div class="carousel-sporrt_text ">
                         <h1 class="sporrt_text">Best sports item shop our</h1>
                         <p  class="lorem_text">There are many variations of passages of Lorem Ipsum available, 
                           but the majority have suffered alteration in some form, by injected randomised words 
                           which don't look even slightly believableThere are many variations of passages of Lorem 
                           Ipsum available, but the majority have suffered alteration in some form, by injected 
                           randomised words which don't look even slightly believable
                          </p>
                      </div>
                   </div>
                   <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                      <div class="img-box">
                         <figure><img src="{% static "images/child-image.png" %}" style="max-width: 100%; border: 15px solid #fff;"/></figure>
                      </div>
                   </div>
                </div>
             </div>
          </div>
          <div class="carousel-item">
             <div class="container">
                <div class="row marginii">
                   <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                      <div class="carousel-sporrt_text ">
                         <h1 class="sporrt_text">Best sports item shop our</h1>
                         <p  class="lorem_text">There are many variations of passages of Lorem Ipsum available, 
                           but the majority have suffered alteration in some form, by injected randomised words 
                           which don't look even slightly believableThere are many variations of passages of 
                           Lorem Ipsum available, but the majority have suffered alteration in some form, by injected
                           randomised words which don't look even slightly believable
                         </p>
                      </div>
                   </div>
                   <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                      <div class="img-box ">
                         <figure><img src="{% static "images/child-image.png" %}" style="max-width: 100%; border: 15px solid #fff;"></figure>
                      </div>
                   </div>
                </div>
             </div>
          </div>
          <div class="carousel-item">
             <div class="container">
                <div class="row marginii">
                   <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                      <div class="carousel-sporrt_text ">
                         <h1 class="sporrt_text">Best sports item shop our</h1>
                         <p  class="lorem_text">There are many variations of passages of 
                           Lorem Ipsum available, but the majority have suffered alteration in 
                           some form, by injected randomised words which don't look even slightly 
                           believableThere are many variations of passages of Lorem Ipsum available, 
                           but the majority have suffered alteration in some form, by injected randomised 
                           words which don't look even slightly believable</p>
                      </div>
                   </div>
                   <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                      <div class="img-box">
                         <figure><img src="{% static "images/child-image.png" %}" style="max-width: 100%; border: 15px solid #fff;"/></figure>
                      </div>
                   </div>
                </div>
             </div>
          </div>
       </div>
    </div>
 </section>

 </div>
 <div style="color:white;">tt</div>
 <div style="color:white;">tt</div>
 <!--end about -->
{% include 'footer.html' %}
 </div>






{% endblock content %}

market/templates/market/cart.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static "css/main.css" %}"> <link
    rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"> <link
    rel="stylesheet" href="{% static "css/style.css" %}">
    <!-- Responsive-->
    <link rel="stylesheet" href="{% static "css/responsive.css" %}">
    <!-- fevicon -->
    <link rel="icon" href="{% static "images/fevicon.png" type="image/gif" %}"
    />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="{% static "css/jquery.mCustomScrollbar.min.css"
    %}">
    <!-- Tweaks for older IEs-->
    <link
      rel="stylesheet"
      href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css"
    />
    <!-- owl stylesheets -->
    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
      media="screen"
    />

    <title>Sock</title>
  </head>
  <body>
    {% include 'shop_navbar.html' %}
    <div class="row">
      <div class="col-lg-12">
        <div class="box-element">
          <a class="btn btn-outline-dark" href="{% url 'market:shop' %}"
            >&#x2190; Continue Shopping</a
          >
          <br />
          <br />
          <table class="table">
            <tr>
              <th>
                <h5>Items: <strong>{{order.cart_items}}</strong></h5>
              </th>
              <th>
                <h5>Total:<strong> ${{order.cart_total}}</strong></h5>
              </th>
              {% if not user.is_authenticated %}
              <th>
                <h4 class="ml-2 text-danger">you have to be logged in so you can add product to the cart! <a class="text-primary" href="{% url 'accounts:login'%}">Login</a></h4>
              </th>
              {% endif %}
              {% if user.is_authenticated %}
              <th>
                <a
                  style="float: right; margin: 5px"
                  class="btn btn-success"
                  href="{% url 'market:checkout' %}"
                  >Checkout</a
                >
              </th>
              {% endif %}
            </tr>
          </table>
        </div>

        <br />
        <div class="box-element">
          <div class="cart-row">
            <div style="flex: 2"></div>
            <div style="flex: 2"><strong>Item</strong></div>
            <div style="flex: 1"><strong>Price</strong></div>
            <div style="flex: 1"><strong>Quantity</strong></div>
            <div style="flex: 1"><strong>Total</strong></div>
          </div>
          {% for item in items %}
          <div class="cart-row">
            <div style="flex: 2">
              <img class="row-image" src="{{item.product.image.url}}" />
            </div>
            <div style="flex: 2">
              <p style="color: #000" class="ml-1">{{item.product.title}}</p>
            </div>
            <div style="flex: 1">
              <p style="color: #000">${{item.product.price|floatformat:2}}</p>
            </div>
            <div style="flex: 1">
              <p class="quantity" style="color: #000">{{item.quantity}}</p>
              <div class="quantity">
                <img
                  data-product="{{item.product.id}}"
                  data-action="add"
                  class="update-cart chg-quantity"
                  src="{% static  'images/arrow-up.png' %}"
                />

                <img
                  data-product="{{item.product.id}}"
                  data-action="remove"
                  class="update-cart chg-quantity"
                  src="{% static  'images/arrow-down.png' %}"
                />
              </div>
            </div>
            <div style="flex: 1">
              <p style="color: #000">${{item.total}}</p>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>

	 <script type="text/javascript" src="{% static "js/cart.js" %}"></script>
   <script>

    function getToken(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
             const cookie = cookies[i].trim();
             // Does this cookie string begin with the name what we want?  
             if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
              }
          }
        }
         return cookieValue;
      }
     const csrftoken = getToken('csrftoken');
   </script>
  </body>
</html>

market/templates/market/checkout.html
{% load static %}

<html lang="en">
	<head>
	  <meta charset="UTF-8">
	  <meta http-equiv="X-UA-Compatible" content="IE=edge">
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <link rel="stylesheet" href="{% static "css/main.css" %}">
	  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
	  <link rel="stylesheet" href="{% static "css/style.css" %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static "css/responsive.css" %}">
      <!-- fevicon -->
      <link rel="icon" href="{% static "images/fevicon.png" type="image/gif" %}" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static "css/jquery.mCustomScrollbar.min.css" %}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <!-- owl stylesheets --> 
      <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
      
	  <title>Sock</title>
	</head>
	<body>
		{% include 'shop_navbar.html' %}
        {% if user.is_authenticated %}
        <div class="row">
            <div class="col-lg-6">
                <div class="box-element" id="form-wrapper">
                    <form id="form">
                        <div id="user-info">
                            <div class="form-field">
                                <input required class="form-control" type="text" name="name" placeholder="Name..">
                            </div>
                            <div class="form-field">
                                <input required class="form-control" type="email" name="email" placeholder="Email..">
                            </div>
                        </div>
                        {% if order.cart_items == 0 %}
                          <h3>you must have product in your cart so you can checkout</h3>
                        {% else %}
                          <div id="shipping-info">
                              <hr>
                              <p style="color:black;">Shipping Information:</p>
                              <hr>
                              <div class="form-field">
                                  <input class="form-control" type="text" required="required" name="address" placeholder="Address..">
                              </div>
                              <div class="form-field">
                                  <input class="form-control" type="text" required="required" name="city" placeholder="City..">
                              </div>
                              <div class="form-field">
                                  <input class="form-control" type="text"  required="required" name="state" placeholder="State..">
                              </div>
                              <div class="form-field">
                                  <input class="form-control" type="text" required="required" name="zipcode" placeholder="Zip code..">
                              </div>
                              <div class="form-field">
                                 <input class="form-control" type="text" required="required" name="country" placeholder="Zip code..">
                              </div>
                          </div>
                          <hr>
                          <input id="form-button" class="btn bg-Primary text-white btn-block" type="submit" value="Continue">
                        {% endif %}
                    </form>
                </div>
    
                <br>
                <div class="box-element hidden" id="payment-info">
                    <small>paypal options:</small>
                    <div id="paypal-button-container"></div>
                    <!--<button id="make-payment" class="payment">make payment</button>-->
                </div>
                
            </div>
    
            <div class="col-lg-6">
                <div class="box-element">
                    <a  class="btn btn-outline-dark" href="{% url 'market:cart' %}">&#x2190; Back to Cart</a>
                    <hr>
                    <h3>Order Summary</h3>
                    <hr>
                    {% for item in items %}
                    <div class="cart-row">
                        <div style="flex:2"><img class="row-image" src="{{item.product.image.url}}"></div>
                        <div style="flex:2"><p style="color:#000;">{{item.product.title}}</p></div>
                        <div style="flex:1"><p style="color:#000;">${{item.product.price|floatformat:2}}</p></div>
                        <div style="flex:1"><p style="color:#000;">{{item.quantity}}</p></div>
                    </div>
                    {% endfor %}
                    <h5>Items: {{order.cart_items}}</h5>
                    <h5>Total: ${{order.cart_total}}</h5>
                </div>
            </div>
        </div>
        {% else %}
        <br><br><br>
         <center><h1>Log in to checkout <a class="text-primary" href="{% url 'login' %}">login</a><h1></center>
        {% endif %}
        <script type="text/javascript">

            function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                     const cookie = cookies[i].trim();
                     // Does this cookie string begin with the name what we want?  
                     if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                      }
                 }
               }
                   return cookieValue;
                }
            const csrftoken = getToken('csrftoken');
        </script>
        
        <script>
            let total = '{{order.cart_total}}'
            let user = '{{request.user}}'

            if (user != 'AnonymousUser'){
                document.getElementById('user-info').innerHTML = ''
            }


            let form = document.getElementById('form')
            form.addEventListener('submit', function (e) {
                e.preventDefault()
                console.log('form submitted...')
                
                document.getElementById('payment-info').classList.remove('hidden')

            }) 
            
            /*
            document.getElementById('make-payment').addEventListener('click', function (e) {
                submitFormData()
                
            })*/

            function submitFormData() {
                console.log("payment button clicked")

                let userFormData = {
                    'name': null,
                    'email': null,
                    'total': total,
                }

                let shippingInfo = {
                    'address': null,
                    'city': null,
                    'state': null,
                    'zipcode': null,
                }

                shippingInfo.address = form.address.value
                shippingInfo.city = form.city.value
                shippingInfo.state = form.state.value
                shippingInfo.zipcode = form.zipcode.value

                if (user == 'AnonymousUser') {
                    userFormData.name = form.name.value
                    userFormData.email = form.email.value
                }
                
                
                let url = '/process_order/'
                fetch(url, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken' : csrftoken,
                    },
                    body:JSON.stringify({'form': userFormData, 'shipping':shippingInfo})
                })
                .then((resopnse) => resopnse.json())
                
                .then((data) => {
                    
                    alert('transaction completed');
                    window.location.href = "{% url 'market:home' %}"
                })
                
            } 

        </script>

        <script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD"></script>

        <script>

            let totalPrice = '{{order.cart_total}}'
            
            // Render the PayPal button into #paypal-button-container
            paypal.Buttons({
                style: {
                    color: 'blue',
                    shape: 'rect',
                    label: 'pay',
                    height: 40
                },
        
                // Set up the transaction
                createOrder: function(data, actions) {
                    return actions.order.create({
                        purchase_units: [{
                            amount: {
                                value: totalPrice
                            }
                        }]
                    });
                },
    
                // Finalize the transaction
                onApprove: function(data, actions) {
                    return actions.order.capture().then(function(orderData) {
                        // Successful capture! For demo purposes:
                        submitFormData()
    

                    });
                }
    
    
            }).render('#paypal-button-container');
        </script>

        
	</body>
</html>	

market/templates/market/shop.html
{% extends 'head.html' %}
{% load static %}
{% block content %}

{% include 'shop_navbar.html' %}


       <!-- plant -->
      <div id="plant" class="section  product">
         <div class="container">
            <div class="row">
               <div class="col-md-12 ">
                  <div class="titlepage">
                     <h2><strong class="black"> Our</strong>  Products</h2>
                     <span>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected randomised words which don't look even slightly believable</span>
                  </div>
               </div>
            </div>
         </div>
      </div>
         <div class="clothes_main section ">
          <div class="container">
            <div class="row">
            {% for product in products %}
               <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12">
                  <div class="sport_product">
                     <figure><img src="{{product.image.url}}" alt="img" style="height:180px; width:300px;"></figure>
                    <h3> $<strong class="price_text">{{product.price}}</strong></h3>
                     <h4><a href="">{{product.title}}</a></h4>
                     <br>
                    <button data-product={{product.id}} data-action="add" class="update-cart text-primary btn btn-outline-secondary add-btn">add to cart</button>
                  </div>
               </div>
            {% endfor %}
            
            <div style="color: white;">page {{page_obj.number}} of {{page_obj.paginator.num_pages}}</div> 
               
            <ul style="margin-left:460px;" class="pagination">
               {% if page_obj.has_previous %}
                 <li><a href="?page=1"><h4 style="color: white;">&laquo; first &nbsp| &nbsp </h4></a></li>
                 <li><a href="?page={{ page_obj.previous_page_number }}"><h4 style="color: white;"> previous</h4></a></li>
               {% endif %}
 
               {% if page_obj.has_next %}
                 <li><a href="?page={{ page_obj.next_page_number }}" style="color: white;" >next &nbsp| &nbsp</a></li>
                 <li><a href="?page={{ page_obj.paginator.num_pages }}" style="color: white;"> last &raquo;</a></li>
               {% endif %}
            </ul>

           </div> 
             </div>
            </div>
           </div>
           
      </div>
      <br/>
      <p style="color:white;">ddd</p>
      <div style="color:white;">ddd</div>

      
   {% include 'footer.html' %}
{% endblock content %}