accounts/urls.py
from django.urls import path, include
from . import views

from django.contrib.auth.views import LogoutView


app_name = 'accounts'

urlpatterns = [
    
    path('register/',views.UserRegisterView.as_view(), name='register'),
    path('login/',views.CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

market/urls.py
from django.urls import path, include
from . import views

app_name = "market"

urlpatterns = [
    path('', views.home, name="home"),
    path('shop/', views.ShopListView.as_view(), name="shop"),
    path('cart/', views.cart, name="cart"),
    path('about/', views.AboutView.as_view(), name="about"),
    path('contanct/', views.ContanctView.as_view(), name="contanct"),
    path('cart/checkout', views.checkout, name="checkout"),
    path('update_item/', views.updateItem, name="updateItem"),
    path('process_order/', views.process_order, name="updateItem"),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('accounts/', include("accounts.urls")),
    path('admin/', admin.site.urls),
    path('', include("market.urls", namespace="market")),
    
    
]

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/footer.html
{% load static %}
<div id="footer" class="Address layout_padding">
    <div class="container">
       <div class="row">
          <div class="col-sm-12">
            <div class="titlepage">
               <div class="main">
                  <h1 class="address_text">Address</h1>
               </div>
            </div>
          </div>
       </div>
            <div class="address_2">
               <div class="row">
                  <div class="col-sm-12 col-md-12 col-lg-4">
                    <div class="site_info">
                       <span class="info_icon"><img src="{% static "images/map-icon.png" %}" /></span>
                       <span style="margin-top: 10px;">No.123 Chalingt Gates, Supper market New York</span></div>
                  </div>
                  <div class="col-sm-12 col-md-12 col-lg-4">
                    <div class="site_info">
                       <span class="info_icon"><img src="{% static "images/phone-icon.png" %}" /></span>
                       <span style="margin-top: 21px;">( +71 7986543234 )</span></div>
                  </div>
                  <div class="col-sm-12 col-md-12 col-lg-4">
                    <div class="site_info">
                       <span class="info_icon"><img src="{% static "images/email-icon.png" %}" /></span>
                       <span style="margin-top: 21px;">demo@gmail.com</span></div>
                  </div>
                  </div> 
               </div>
            </div>
               <div class="menu_main">
                  <div class="menu_text">
                     <ul>
                        <li class="active"><a href="{% url 'market:home'%}">Home</a></li>                         
                        <li><a href="about.html">About</a></li>
                        <li><a>Link</a></li>
                        <li><a href="{% url 'market:shop'%}">Shop</a></li>
                        <li><a href="contact.html">Contact Us</a></li>
                     </ul>
                  </div>
               </div>
    </div>
 </div>

   <!-- end Contact Us-->
   <!-- footer start-->
   <div id="plant" class="footer layout_padding">
      <div class="container">
         <p>© 2022 All Rights Reserved</p>
      </div>
   </div>

templates/head.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <title>Sock</title>

      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      
      <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
      <link rel="stylesheet" href="{% static "css/style.css" %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static "css/responsive.css" %}">
      <!-- fevicon -->
      <link rel="icon" href="{% static "images/fevicon.png" type="image/gif" %}" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static "css/jquery.mCustomScrollbar.min.css" %}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <!-- owl stylesheets --> 
      <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
      
   </head>
   <!-- body -->
   <body class="main-layout">
      <!-- loader  -->
      

      {% block content %}
      
      
      {% endblock content %}


       <!-- Javascript files-->
       <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
       <script type="text/javascript" src="{% static "js/popper.min.js" %}"></script>
       <script type="text/javascript" src="{% static "js/bootstrap.bundle.min.js" %}"></script>
       <script type="text/javascript" src="{% static "js/jquery-3.0.0.min.js" %}"></script>
       <script type="text/javascript" src="{% static "js/plugin.js" %}"></script>
       <!-- sidebar -->
       <script type="text/javascript" src="{% static "js/jquery.mCustomScrollbar.concat.min.js" %}"></script>
       <script type="text/javascript" src="{% static "js/custom.js" %}"></script>
       <!-- javascript --> 
       <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
       <script type="text/javascript" type="text/javascript" src="{% static "js/cart.js" %}"></script>

       <script>
   
         function getToken(name) {
         let cookieValue = null;
         if (document.cookie && document.cookie !== '') {
             const cookies = document.cookie.split(';');
             for (let i = 0; i < cookies.length; i++) {
                  const cookie = cookies[i].trim();
                  // Does this cookie string begin with the name what we want?  
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                     cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                     break;
                  }
              }
            }
            return cookieValue;
         }
        const csrftoken = getToken('csrftoken');
       </script> 
    </body>
</html>

templates/navbar.html
{% load static %}
<style>
   .wrapper{
   position: relative;
   }
   .wrapper small{
   position: absolute;
   top: -6px;
   right: 24px; 
   }
</style>
<body>    
 <!-- end loader -->
 <!-- header -->
 <header class="section">
    <!-- header inner -->
    <div class="header">
      <div class="container">
         <div class="row">
            <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
               <div class="full">
                  <div class="center-desk">
                     <div class="logo"> <a href="{% url 'market:home'%}"><img src="{% static "images/logo.png" %}" alt="#"></a> </div>
                  </div>
               </div>
            </div>
            <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
               <div class="menu-area">
                  <div class="limit-box">
                     <nav class="main-menu">
                        <ul class="menu-area-main">
                           <li> <a href="{% url 'market:home'%}">Home</a> </li>
                           <li> <a href="{% url 'market:about'%}">About</a> </li>
                           {% if user.is_authenticated %}
                             <li><a href="{% url 'accounts:logout'%}">Logout</a></li>
                           {% else %}
                             <li><a href="{% url 'accounts:register'%}">Register</a></li>
                           {% endif %}
                           <li><a href="{% url 'market:shop'%}">Shop</a></li>
                           <li><a href="{% url 'market:contanct'%}">Contact Us</a></li>
                           <li class="last">
                              <a href="{% url 'market:cart' %}"  class="wrapper">
                              <img src="{% static "images/cart.png" %}" style="height:20px; width:24px;" alt="icon">
                              <small>{{cartItems}}</small>
                              </a>
                          </li>
                        </ul>
                     </nav>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- end header inner -->
</header>
 <!-- end header -->
 <section >
    <div id="main_slider" class="section carousel slide banner-main" data-ride="carousel">
       <ol class="carousel-indicators">
          <li data-target="#main_slider" data-slide-to="0" class="active"></li>
          <li data-target="#main_slider" data-slide-to="1"></li>
          <li data-target="#main_slider" data-slide-to="2"></li>
       </ol>
       <div class="carousel-inner">
          <div class="carousel-item active">
             <div class="container">
                <div class="row marginii">
                   <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                      <div class="carousel-caption ">
                         <h1>Welcome to <strong class="color">Sock Shop</strong></h1>
                         <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour</p>
                         <a class="btn btn-lg btn-primary" href="{% url 'market:shop' %}" role="button">Buy Now</a>
                         <a class="btn btn-lg btn-primary" href="{% url 'market:about'%}" role="button">About </a>
                      </div>
                   </div>
                   <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                      <div class="img-box">
                         <figure><img src="{% static "images/boksing-gloves.png" %}" alt="img"></figure>
                      </div>
                   </div>
                </div>
             </div>
          </div>
          <div class="carousel-item">
             <div class="container">
                <div class="row marginii">
                   <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                      <div class="carousel-caption ">
                         <h1>Welcome to <strong class="color">Our Shop</strong></h1>
                         <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour</p>
                         <a class="btn btn-lg btn-primary" href="{% url 'market:shop' %}" role="button">Buy Now</a>
                         <a class="btn btn-lg btn-primary" href="{% url 'market:about' %}" role="button">About</a>
                      </div>
                   </div>
                   <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                      <div class="img-box ">
                         <figure><img src="{% static "images/boksing-gloves.png" %}" alt="img"/></figure>
                      </div>
                   </div>
                </div>
             </div>
          </div>     
    </div>
 </section>
</body>

templates/shop_navbar.html
{% load static %}
<style>
   .wrapper{
   position: relative;
   }
   .wrapper small{
   position: absolute;
   top: -6px;
   right: 24px; 
   }
</style>
<nav class="navbar navbar-light bg-primary">
    <div class="container">
    <div class="logo">
      <a class="navbar-brand " href="{% url 'market:home'%}">
         <img src="{% static "images/logo.png" %}" alt="" >
      </a>
    </div>
    <nav class="main-menu">
       <div>
          <ul class="menu-area-main mb-0 ">
             <li class="mt-4"> <a href="{% url 'market:home'%}">Home</a> </li>
             <li class="mt-4"> <a href="{% url 'market:about' %}">About</a></li>
             {% if user.is_authenticated %}
             <li class="mt-4"><a href="{% url 'accounts:logout'%}">Logout</a></li>
             {% else %}
             <li class="mt-4"><a href="{% url 'accounts:register'%}">Register</a></li>
             {% endif %}
             <li class="mt-4 "><a href="{% url 'market:shop'%}">Shop</a></li>
             <li class="mt-4"><a href="{% url 'market:contanct'%}">Contact Us</a></li>
             <li class="last mt-4 ">
               <a href="{% url 'market:cart' %}" class="wrapper">
               <img src="{% static "images/cart.png" %}" style="height:22px; width:24px;" alt="icon">
               <small>{{cartItems}}</small>
               </a>
            </li>
          </ul>
       </div>
    </nav>
  </div>
</nav>